### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by chasingegg** [cgtuebingen/ggnn#1]
Hello, I am very interested in your wonderful work! After reading your paper, I have some questions to ask.
1. You put emphasize on the construction time reduction, but how is that achieved, you did not clarify it, it is more like a partition-and-merge way, partition is fast because the subgraphs are small, and when we merge the subgraphs, I think in HNSW, each node has to perform a query to link the neighbors, but here you sample some vertices as the top layer to do this, is this the main reason for reducing the construction time?
2. How to add symmetric links after we have a KNN-graph? I know the rule in paper section4.3 that how x and z connected, but how we get such candidates?
3. I am a little bit confused how you perform queries, which is mentioned in paper section 4.1(last paragraph), 4.2, 4.5, do we have to go down from the top layer to bottom layer? Actually in these three sections, you are saying different things for how to perform queries...
4. Why your algorithm is suitable for GPU? Or I say why HNSW-gpu(if we reimplement hnsw on gpu) is less efficient?
5. You did not report your memory consumption, but I think it is huge even if you have 8 GPUs... I assume 8GPUs have about 100GB device memory, how does it run on 1B data?

**Comment by grohf** [comment]
Hey, 
actually most of your questions are covered in our supplementary work. We should definitely add that to arxiv or create a project page already.

Meanwhile, I will try to answer them here:

1. The main reason is that all 'queries' are performed in parallel for each stage and merging is also performed by querying. The selection isn't that important even random selection performs well enough in most cases. Important is that there are links at all, but we also ensure them by symmetric linking.

2. The k-list of NN for every point (also during construction) consist of two parts: k = k_nn + k_sym, where k_nn is the list of NN that we rely on and k_sym is a part that is allowed to be written by symmetric linking.
Candidates are all points z_i in the k_nn list of x that do not have a path back. Thus, an inverese query is performed starting from z_i and query point x.

3. Yes, there are different strategies. During the construction, we always go from top to bottom over all layers, that makes it very robust and results in good quality, even if the connectivity is still not perfect.
On the final query, at this point the graph has already a good connectivity, we start at the top points but directly on the bottom layer (all points also exist on the bottom layer).
This little trick makes it faster without losing quality.

4. Our algorithm do not perform global updates, only local. You can see it like that: The hierarchy gives us some global view, but we only perform local/neighborhood optimization. And those can be performed all in parallel with a fixed K -> GPU friendly.

5. We perform a sharding with about 10GB of data per GPU and iteration. The index is relatively small compared to the data since only the ids of the NN are stored (K = 20 and L=4).

I hope this clarifies some of your points. With the code released this should also be easier to understand.

**Comment by chasingegg** [comment]
Thank you for your reply! So I think because HNSW needs more global synchronizations, the construction is slow. In ggnn's construction, the top point choose some neighbors at top layer, and go down to corresponding partition in the bottom layer where these neighbors are located, and perform a more concise query to connect the neighbors, am I right?
PS, I am looking forward to your code and supplementary work to be released soon!

**Comment by grohf** [comment]
In general, yes. 
CPU-graph based methods adding (or removing) points and edges one after each other in a global sense. However, in our implementation HNSW is already fast compared to the others (even so they report sometimes differently).

We start for each point with a more local graph structure that gets wider on every iteration due to merging, In particular, points on the bottom layer always have the same number of neighbors, but after each merge step the potential set of points is growth-rate [g] times larger.

**Comment by chasingegg** [comment]
Sorry to disturb you again, do you have tested your algorithm on CPU? It should also gain much improvement on CPU.
