### ISSUE TITLE
How to get the latest paper?

### ISSUE THREAD

**Issue by kangzhao2** [cgtuebingen/ggnn#8]
Hi guys:

I've read the v3 of GGNN on Arxiv: https://arxiv.org/pdf/1912.01059v3.pdf, but I didn't find the comparison with the method: SONG.

I want to know how to get the latest version of GGNN paper?

Kang

**Comment by LukasRuppert** [comment]
Hi,

the paper is still undergoing review and we will update the version on ArXiv upon acceptance.
According to https://journals.ieeeauthorcenter.ieee.org/become-an-ieee-journal-author/publishing-ethics/guidelines-and-policies/submission-and-peer-review-policies/ it should also be allowed to update it to the version that is currently undergoing review,
so this is something I need to discuss with my co-authors.

Best,
Lukas

**Comment by kangzhao2** [comment]
Hope to see your latest paper soon :)

**Comment by LukasRuppert** [comment]
Sorry for the huge delay.

You can now get the accepted version on our university's webpage:
https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/computergrafik/lehrstuhl/veroeffentlichungen/publications-since-2012/ggnn-graph-based-gpu-nearest-neighbor-search/

We will update the ArXiv version shortly.

The final published version will only be available via IEEE: (except for changes by the editor this should have the same contents)
https://doi.org/10.1109/TBDATA.2022.3161156

**Comment by kangzhao2** [comment]
Thanks very much
